[package]
name = "rayonetta"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
env_logger = "0.11.5"
image = "0.25.2"
lazy_static = "1.5.0"
log = "0.4.22"
rand = "0.8.5"
rayon = "1.10.0"
